name: CI

on:
  push:
    branches:
      - main
    paths:
      - "pcb/*.kicad_*"
      - "kibot.yml"
      - ".github/workflows/ci.yml"

jobs:
  check:
    name: Check
    uses: ./.github/workflows/kibot-check.yml
    with:
      config-file: kibot.yml
      board-file: pcb/NFC2USB.kicad_pcb

  docs:
    name: Docs
    needs: check
    uses: ./.github/workflows/kibot-docs.yml
    with:
      config-file: kibot.yml
      board-file: pcb/NFC2USB.kicad_pcb
