name: Pull Request

on:
  pull_request:
    paths:
      - "pcb/*.kicad_*"
      - "kibot.yml"
      - ".github/workflows/pull-request.yml"

jobs:
  check:
    name: Check
    uses: ./.github/workflows/kibot-check.yml
    with:
      config-file: kibot.yml
      board-file: pcb/NFC2USB.kicad_pcb
