name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    uses: ./.github/workflows/release-please-workflow.yml@main
    with:
      config-file: release.kibot.yml
      board-file: pcb/NFC2USB.kicad_pcb
